#
# Not that http://localhost:8080/swagger may give you an error, because it's hard-coded to query localhost:8080/contacts/swagger
# Basically using docker-toolbox + windows7 means you're going for a non-localhost URL.
# You'll need to wait awhile as well for mysql to come up
# Check the DB has been created using the mysql console
# docker exec -it soiltype_auth_mysql mysql -uroot -ppassword
version: '3'
services:
  mysql:
    image: mysql/mysql-server:5.6
    container_name: soiltype_auth_mysql
    hostname: soiltype_auth_mysql.local
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: soiltype_auth
      MYSQL_USER: soiltype_auth
      MYSQL_PASSWORD: soiltype_auth
    ports:
      - '3306:3306'
    # Mount and execute our SQL files.
    volumes:
      - ./src/main/sql:/docker-entrypoint-initdb.d

  interlok:
    #
    # If you just want to mount the config then of course, you can...
    image: adaptrislabs/interlok-soiltype-demo:latest
    container_name: soiltype_auth
    hostname: soiltype_auth.local
    environment:
      JVM_ARGS: -Xmx1G
      JAVA_OPTS: -Dinterlok.db.url=jdbc:mysql://mysql:3306/soiltype_auth -Dinterlok.db.user=soiltype_auth -Dinterlok.db.password=soiltype_auth -Dinterlok.api.host=localhost:8080
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    links:
      - mysql:mysql
